<script type="text/javascript" src="{{asset('frontend/assets/js/jquery/jquery.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/jquery/jquery-migrate.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/jquery.appear.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/modernizr.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/jquery.plugin.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/owl.carousel.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/jquery.waypoints.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/fluidvids.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/ScrollToPlugin.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/parallax.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/jquery.waitforimages.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/jquery.prettyPhoto.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/jquery.easing.1.3.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/packery-mode.pkgd.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules/plugins/jquery.mousewheel.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/modules.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/mediaelement/mediaelement-and-player.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/mediaelement/mediaelement-migrate.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/underscore.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/jquery/ui/core.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/jquery/ui/widget.min.js')}}"></script>
<script type="text/javascript" src="{{asset('frontend/assets/js/jquery/ui/tabs.min.js')}}"></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/jquery/ui/accordion.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/mediaelement/wp-mediaelement.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/hoverIntent.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/wp-embed.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/jquery-blockui/jquery.blockUI.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/includes/js/scripts.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/membership.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/modules/plugins/nouislider.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/modules/plugins/typeahead.bundle.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/modules/plugins/bloodhound.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/tours.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/js-cookie/js.cookie.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/frontend/woocommerce.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/frontend/cart-fragments.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/lib/bower/isotope/dist/isotope.pkgd.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/select2/select2.full.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/shortcodes/countdown/assets/js/plugins/jquery.countdown.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/shortcodes/counter/assets/js/plugins/counter.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/shortcodes/counter/assets/js/plugins/absoluteCounter.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/shortcodes/custom-font/assets/js/plugins/typed.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/shortcodes/full-screen-sections/assets/js/plugins/jquery.fullPage.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/shortcodes/vertical-split-slider/assets/js/plugins/jquery.multiscroll.min.js')}}'></script>
<script type='text/javascript' src='{{asset('frontend/assets/js/js_composer_front.min.js')}}'></script>
